language: python
python:
    - 2.7
cache: pip
virtualenv:
    system_site_packages: true

addons:
    apt:
        packages: [ python-dev, python-scipy, gfortran, libatlas-dev, libopenblas-dev ]


before_install:
    - "pip install scipy matplotlib pyyaml progressbar setuptools flake8"
    - "easy_install pyavl"
    - "curl -s http://kinherd.org/fomosto-qseis-2006a.tar.gz | tar zvx" 
    - "cd fomosto-qseis-2006a; ./configure; make; cd ..; export PATH=$PATH:`pwd`/src"

before_script:
    - "flake8 src/ apps/ --exit-zero"

install:
    - "pip install ."

script:
    - "python test/test_all.py"

notifications:
    email: false
