language: python

sudo: required

before_install:
    - sudo apt-get install make git python-dev python-setuptools
    - sudo apt-get install python-numpy python-numpy-dev python-scipy python-matplotlib
    - sudo apt-get install python-yaml python-progressbar
    - sudo easy_install pyavl

