language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          cache: pip
          virtualenv:
              system_site_packages: true

addons:
    apt:
        packages: [ python-dev, python-scipy, gfortran, libatlas-dev, libopenblas-dev, python-matplotlib, python-yaml, python-tk ]

before_install:
    - "pip install progressbar setuptools flake8"
    - "easy_install pyavl"
    - "curl -s http://kinherd.org/fomosto-qseis-2006a.tar.gz | tar zvx" 
    - "cd fomosto-qseis-2006a; ./configure; make; export PATH=$PATH:`pwd`/src; cd .."

before_script:
    - "flake8 src/ apps/ --exit-zero"

install:
    - "sudo python setup.py install"

script:
    - "python test/test_all.py"

notifications:
    email: false
