language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          cache: pip
          virtualenv:
              system_site_packages: true
        - os: osx
          osx_image: xcode7.3
          language: generic

addons:
    apt:
        packages: [ python-dev, python-scipy, gfortran, libatlas-dev, libopenblas-dev, python-matplotlib, python-yaml, python-tk, libyaml-dev, poppler-utils, ghostscript, imagemagick ]

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink libyaml; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc libyaml; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install matplotlib; fi
    - pip install progressbar setuptools flake8 pyyaml coveralls
    - easy_install pyavl
    - git clone https://github.com/pyrocko/fomosto-qseis
    - cd fomosto-qseis-2006a; ./autoreconf -i; ./configure; make; export PATH=$PATH:`pwd`/src; cd ..
    - git clone https://github.com/pyrocko/fomosto-psgrn-pscmp
    - cd fomosto-psgrn-pscmp; ./autoreconf -i; ./configure; make; export PATH=$PATH:`pwd`/src; cd ..
    - git clone https://github.com/pyrocko/fomosto-qssp.git
    - cd fomosto-qssp; ./autoreconf -i; ./configure; make; export PATH=$PATH:`pwd`/src; cd ..

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then flake8 src/ apps/ test/ ; fi

install:
    - sudo python setup.py install

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python test/test_all.py ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coverage run --source=pyrocko test/test_all.py ; fi

after_success:
    - coveralls

notifications:
    email: false
