sudo: required

language: python
python: 2.7

before_install:
    - sudo apt-get install make git python-dev python-setuptools python-numpy python-numpy-dev python-scipy python-matplotlib python-yaml python-progressbar
    - sudo easy_install pyavl

install:
    - sudo python setup.py install

script:
    - sudo python test/test_all.py

notifications:
    email: false
